In [6]:
import numpy as np

x= np.array([1,2,3,4]) #This is how we create an array
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
y= [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [11]:
# How to convert a list into array
import numpy as np
a= [3,2,4,8]
b= np.array(a)
print(b)


[3 2 4 8]


In [17]:
# Create a list in which user will insert some values and then convert it into an array:
l= []
for i in range(1,4):
    abc = input("Enter value")
    l.append(abc)
    
print(np.array(l))

[<PyodideFuture pending cb=[WebLoop._decrement_in_progress()]>
 <PyodideFuture pending cb=[WebLoop._decrement_in_progress()]>
 <PyodideFuture pending cb=[WebLoop._decrement_in_progress()]>]


Enter value 8
Enter value 7
Enter value 5


In [27]:
#how to create Multidiamensional array:
ar3 = np.array([[[1,2,3,4], [5,1,3,2], [1,2,3,4]]])
print(ar3)
print(ar3.ndim) # ndim is used to find the number of diamensions.

print()
#ShortCut to create Multidiamensional Array using ndmin:
arn = np.array([1,2,3,4], ndmin = 10) # ndmin will execute 10 diamensional array
print(arn)
print(arn.ndim)

[[[1 2 3 4]
  [5 1 3 2]
  [1 2 3 4]]]
3

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [33]:
#Zeros
arz = np.zeros(3)
print(arz)

arz1 = np.zeros((3,4))
print(arz1)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
#Ones
aro= np.ones(4)
print(aro)

aro1 = np.ones((4,5))
print(aro1)


#Empty : empty present the value of previous execution
arem= np.empty(4)
print(arem)

[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1. 1.]


In [46]:
# Range
arrn= np.arange(4)
print(arrn)

# Diagonal
ardn = np.eye(4)
print(ardn)

[0 1 2 3]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
# Random
# Rand: it executes numbers between 0 & 1
ran1= np.random.rand(4)
print(ran1)

ran2 = np.random.rand(3,4)
print(ran2)

print()

#Randn : it show numbers (positive and negative) near 0
ran3 = np.random.randn(4)
print(ran3)

ran4 = np.random.randn(3,4)
print(ran4)


[0.77207869 0.93781131 0.72104676 0.24746365]
[[0.69536555 0.95362272 0.62811726 0.62675959]
 [0.74816786 0.15446122 0.76128925 0.91032441]
 [0.73905393 0.89659297 0.01449412 0.71551264]]

[ 0.37745549 -1.06383865  0.37177137  0.79430146]
[[ 1.3649922  -0.05262969 -0.90625502  1.00988939]
 [-1.36417097  0.10213098  0.79842461 -2.06212918]
 [ 0.2180363   1.10455923 -0.40278873 -0.74352211]]


In [57]:
#ranf: it executes numbers between [0 1) that means 0 is included but it will be less than 1
raf= np.random.ranf(4)
print(raf)

raf1= np.random.ranf((3,4))
print(raf1)

print()

#randint: it shows the numbers between given range: np.random.randint(min, max, number of results)
ranit = np.random.randint(5, 20, 4)
print(ranit)

[0.08797851 0.10707293 0.0203824  0.01549488]
[[0.66912282 0.03136577 0.6864166  0.74390602]
 [0.72503655 0.05495181 0.53988258 0.32710661]
 [0.64715688 0.89325993 0.29766241 0.0703655 ]]

[13  7 17  8]


In [1]:
# Data type
import numpy as np
a= np.array([2,4,15,24])
print(a)
print(a.dtype)

b= np.array([1.3, 1.5, 1.8])
print(b)
print(b.dtype)

#if we have to change the data type of a
a= np.array([2,4,15,24], dtype = np.int8)
print(a)
print(a.dtype)

[ 2  4 15 24]
int32
[1.3 1.5 1.8]
float64
[ 2  4 15 24]
int8


In [2]:
#Change a data type using function
c= np.array([4,3,6,9])
print(c)
print(c.dtype)
d= np.float32(c)
print(d)
print(d.dtype)

#another method to change data type
print()
e=c.astype(float)
print(e)
print(e.dtype)

[4 3 6 9]
int32
[4. 3. 6. 9.]
float32

[4. 3. 6. 9.]
float64
